FROM node:16

RUN npm install -g pnpm@^7

WORKDIR /src

COPY .npmrc pnpm-lock.yaml ./
RUN pnpm fetch

COPY . ./

RUN pnpm -F flight-mobile... install --offline
RUN pnpm -F flignt-mobile... build-production

WORKDIR /src/apps/flight-mobile

CMD ["sh", "-c", "STREAM_LOG_TO_GCP=true node -r newrelic -r dotenv/config .output/server/index.mjs dotenv_config_path=.env.production dotenv_config_debug=true"]