FROM node:16

RUN npm install -g pnpm@^7

WORKDIR /src

COPY .npmrc pnpm-lock.yaml ./
RUN pnpm fetch

COPY . ./

RUN pnpm -F flight-mobile... install --offline
RUN pnpm -F flight-mobile... build-staging

CMD ["sh", "-c", "STREAM_LOG_TO_GCP=true node -r dotenv/config apps/flight-mobile/.output/server/index.mjs dotenv_config_path=apps/flight-mobile/.env.staging dotenv_config_debug=true"]