FROM node:16

RUN npm install -g pnpm@^8

WORKDIR /src

COPY .npmrc pnpm-lock.yaml ./
RUN pnpm fetch

COPY . ./

RUN pnpm -F main-desktop-app... install --offline
RUN pnpm -F main-desktop-app... build-production
RUN rm -rf .nuxt/dist/**/*.map

WORKDIR /src/apps/main-desktop

CMD ["sh", "-c", "STREAM_LOG_TO_GCP=true node -r dotenv/config .output/server/index.mjs dotenv_config_path=.env.production dotenv_config_debug=true"]