export default [
  [
    {
      id: 'JT',
      url: 'lion-air.webp',
      label: 'Lion Air',
      path: 'lion-air',
      color: '#ec0000',
    },
    {
      id: 'QG',
      url: 'citilink.webp',
      label: 'Citilink',
      path: 'citilink',
      color: '#52b650',
    },
    {
      id: 'SJ',
      url: 'sriwijaya.webp',
      label: 'Sriwijaya',
      path: 'sriwijaya',
      color: '#45508f',
    },
    {
      id: 'GA',
      url: 'garuda-indonesia.webp',
      label: 'Garuda Indonesia',
      path: 'garuda-indonesia',
      color: '#54b2cb',
    },
    {
      id: 'IW',
      url: 'wings-air.webp',
      label: 'Wings Air',
      path: 'wings-air',
      color: '#eb0000',
    },
    {
      id: 'QZ',
      url: 'air-asia.webp',
      label: 'Air Asia',
      path: 'air-asia',
      color: '#e32526',
    },
    {
      id: 'IN',
      url: 'nam.webp',
      label: 'Nam Air',
      path: 'nam-air',
      color: '#0a0a48',
    },
    {
      id: 'ID',
      url: 'batik-air.webp',
      label: 'Batik Air',
      path: 'batik-air',
      color: '#d41b60',
    },
    {
      id: 'TR',
      url: 'scoot.webp',
      label: 'Scoot',
      path: 'scoot',
      color: '#ffe900',
    },
    {
      id: 'MH',
      url: 'malaysia-airlines.webp',
      label: 'Malaysia Airlines',
      path: 'malaysia-airlines',
      color: '#80bbed',
    },
  ],
  [
    {
      id: 'SQ',
      url: 'singapore-airlines.webp',
      label: 'Singapore Airlines',
      path: 'singapore-airlines',
      color: '#00266b',
    },
    {
      id: 'CX',
      url: 'cathay-pacific.webp',
      label: 'Cathay Pacific Airways',
      path: 'cathay-pacific-airways',
      color: '#006565',
    },
    {
      id: 'KL',
      url: 'klm.webp',
      label: 'KLM',
      path: 'klm',
      color: '#0da6e0',
    },
    {
      id: 'VN',
      url: 'vietnam-airlines.webp',
      label: 'Vietnam Airlines',
      path: 'vietnam-airlines',
      color: '#0584aa',
    },
    {
      id: 'FD',
      url: 'air-asia.webp',
      label: 'Thai AirAsia',
      path: 'thai-airasia',
      color: '#ff0008',
    },
    {
      id: 'QF',
      url: 'qantas.webp',
      label: 'Qantas',
      path: 'qantas',
      color: '#394f59',
    },
    {
      id: 'CI',
      url: 'china-airlines.webp',
      label: 'China Airlines',
      path: 'china-airlines',
      color: '#97a7e2',
    },
    {
      id: 'KE',
      url: 'korean-air.webp',
      label: 'Korean Air',
      path: 'korean-air',
      color: '#0d58ad',
    },
    {
      id: 'BR',
      url: 'eva-air.webp',
      label: 'EVA Air',
      path: 'eva-air',
      color: '#058341',
    },
    {
      id: 'CZ',
      url: 'china-southern-airlines.webp',
      label: 'China Southern Airlines',
      path: 'china-southern-airlines',
      color: '#062d70',
    },
  ],
  [
    {
      id: 'PG',
      url: 'bangkok-airways.webp',
      label: 'Bangkok Airways',
      path: 'bangkok-airways',
      color: '#264aa1',
    },
    {
      id: 'PR',
      url: 'philippine-airlines.webp',
      label: 'Philippine Airlines',
      path: 'philippine-airlines',
      color: '#022a67',
    },
    {
      id: 'CA',
      url: 'air-china.webp',
      label: 'Air China',
      path: 'air-china',
      color: '#0a417a',
    },
    {
      id: 'HX',
      url: 'hong-kong-airlines.webp',
      label: 'Hong Kong Airlines',
      path: 'hong-kong-airlines',
      color: '#d60316',
    },
    {
      id: 'JQ',
      url: 'jetstar.webp',
      label: 'Jetstar',
      path: 'jetstar',
      color: '#F78D5A',
    },
    {
      id: 'JL',
      url: 'japan-airlines.webp',
      label: 'Japan Airlines',
      path: 'japan-airlines',
      color: '#D7061A',
    },
    {
      id: 'NH',
      url: 'ana.webp',
      label: 'All Nippon Airways',
      path: 'all-nippon-airways',
      color: '#114A8D',
    },
    {
      id: 'MU',
      url: 'china-eastern-air.webp',
      label: 'China Eastern Airlines',
      path: 'china-eastern-airlines',
    },
    {
      id: 'BI',
      url: 'royal-brunei.webp',
      label: 'Royal Brunei Airlines',
      path: 'royal-brunei-airlines',
      color: '#ffe319',
    },
    {
      id: 'OZ',
      url: 'asiana-airlines.webp',
      label: 'Asiana Airlines',
      path: 'asiana-airlines',
      color: '#E30214',
    },
  ],
  [
    {
      id: 'TG',
      url: 'thai-airways.webp',
      label: 'Thai Airways',
      path: 'thai-airways',
      color: '#4B225B',
    },
    {
      id: 'FM',
      url: 'shanghai-airlines.webp',
      label: 'Shanghai Airlines',
      path: 'shanghai-airlines',
      color: '#DE0039',
    },
    {
      id: 'KA',
      url: 'cathay-dragon.webp',
      label: 'Cathay Dragon',
      path: 'cathay-dragon',
      color: '#BA0030',
    },
    {
      id: 'FY',
      url: 'firefly.webp',
      label: 'Firefly',
      path: 'firefly',
      color: '#F2641A',
    },
    {
      id: 'MI',
      url: 'silk-air.webp',
      label: 'SilkAir',
      path: 'silk-air',
      color: '#009484',
    },
    {
      id: '5J',
      url: 'cebu-pacific.webp',
      label: 'Cebu Pacific',
      path: 'cebu-pacific',
      color: '#06A6E0',
    },
    {
      id: 'MF',
      url: 'xiamen-air.webp',
      label: 'Xiamen Air',
      path: 'xiamen-air',
      color: '#008AC5',
    },
    {
      id: 'WE',
      url: 'thai-smile.webp',
      label: 'Thai Smile',
      path: 'thai-smile',
      color: '#F07623',
    },
  ],
];
