name: flight_mobile_new_relic_change_tracking
on:
  push:
    tags:
      - flight-mobile/*

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      # This step builds a var with the release tag value to use later
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      # This step creates a new Change Tracking Marker
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: ${{ secrets.FLIGHT_MOBILE_NEW_RELIC_API_KEY }}
          guid: ${{ secrets.FLIGHT_MOBILE_NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: '${{ env.RELEASE_VERSION }}'
          user: '${{ github.actor }}'
